.TH "gseptica" "1" "December 2009" "GTK Applications" ""
.SH "NAME"
.LP 
GSeptica \- a GTK card game

.SH "SYNOPSIS"
.B gseptica 

.SH "DESCRIPTION"
.LP 
\fIGSeptica\fP is the GTK implementation of a popular card game, known in 
Romania as septica.

.SH "AUTHORS"
.LP
Written by Mihai Varzaru <mihaiv@gmail.com>.
.LP 

